### ISSUE TITLE
can not install on windows 11 

### ISSUE THREAD

**Issue by morganwang010** [spacedriveapp/spacedrive#1531] opened 2023-10-12 07:51 UTC
### Describe the bug

Spacedrive-windows-x86_64.msi, this install package can not be installed successfully, report the error code 2502 , 2503. 
![image](https://github.com/spacedriveapp/spacedrive/assets/7390456/39ce0af0-a7f9-4437-9ba6-db007e94803f)

### Reproduction

1,downlowad the windows installer package
2,execute the msi package
3,got the error

### Platform and versions

```Shell
OS： windows 11 
version : 22h2
```

**Comment by gedeondoescode** [comment] 2023-10-12 23:36
I'm not sure if you've already tried this but can you try running it as Administrator and see if anything changes

**Comment by HeavenVolkoff** [comment] 2023-10-14 06:57
As far as I know, this issue is likely either the installation process or the user lacking access to the temporary folder required for extracting the application data before copying it to the final installation location. You can attempt one of the following solutions:

- Run the installer as an administrator.
- Move the installer to a different directory, such as your home directory or C: drive.
- Make sure you have the necessary permissions to access the temporary directory. You can find instructions on how to do this [here](https://help.krisp.ai/hc/en-us/articles/8083286001820-Error-during-installation-2502-and-2503-#h_01GVJNAPWJ23Q18ZMWD8ZX79N7)

**Comment by Diselorya** [comment] 2023-12-01 20:00
![image](https://github.com/spacedriveapp/spacedrive/assets/47026572/39795e2c-91e8-433a-8811-87eb7413d5c4)
Me too, but another error code.

Tried, but not work

> 据我所知，这个问题可能是安装过程或用户在将应用程序数据复制到最终安装位置之前无法访问提取应用程序数据所需的临时文件夹。您可以尝试以下解决方案之一：
> 
> * 以管理员身份运行安装程序。
> * 将安装程序移动到其他目录，例如主目录或 C： 驱动器。
> * 确保您具有访问临时目录所需的权限。您可以[在此处](https://help.krisp.ai/hc/en-us/articles/8083286001820-Error-during-installation-2502-and-2503-#h_01GVJNAPWJ23Q18ZMWD8ZX79N7)找到有关如何执行此操作的说明

**Comment by HeavenVolkoff** [comment] 2023-12-01 20:12
> Me too, but another error code 2755.

2755 seems to also be an error related to missing permissions:
https://community.withsecure.com/en/kb/articles/29749-error-2755-upon-windows-business-suite-product-installation

You said you tried running with admin privileges, did you get the exact same error? If so, how is your Windows setup? What version and edition of Windows are you using (include patch number if possible) ? Is it a personal computer or a company issued one? Is your admin account a local one or a remote one?

**Comment by Diselorya** [comment] 2023-12-01 20:44
Thanks, it works.
The problem is I cannot find "Run with administrator privileges" in the right-click menu of the. msi installation package.
I find a way to run as admin, then it works:
1. Run cmd.exe as admin.
2. msiexec /package Spacedrive-windows-x86_64.msi


> > Me too, but another error code 2755.
> 
> 2755 seems to also be an error related to missing permissions: https://community.withsecure.com/en/kb/articles/29749-error-2755-upon-windows-business-suite-product-installation
> 
> You said you tried running with admin privileges, did you get the exact same error? If so, how is your Windows setup? What version and edition of Windows are you using (include patch number if possible) ? Is it a personal computer or a company issued one? Is your admin account a local one or a remote one?

**Comment by Raghav-45** [comment] 2024-04-16 05:11
I think this issue has been resolved, so let's close it.

**Closed** 2024-04-16 15:14 UTC
Labels: kind/bug, status/needs-fix-confirmation

**Comment by stephandeckers** [comment] 2024-10-28 06:25
For me it was caused by trying to run the installer on a Junction pointing to a folder, once running in an actual folder it was solved
