### ISSUE TITLE
Appimage is completely missing in new 3.0 release?

### ISSUE THREAD

**Issue by 32bitx64bit** [spacedriveapp/spacedrive#2565] opened 2024-06-25 06:49 UTC
### Describe the bug

Hi, recently found this project, I use a arch based system and kinda need a appimage to use this.
As currently Ia m stuck on using the last0.2.14

### Reproduction

Go to download page.
appimage missing.

### Platform and versions

```Shell
Linux arch.
```

**Comment by HeavenVolkoff** [comment] 2024-06-25 20:09
Hello @32bitx64bit. Unfortunately we have dropped AppImage releases on Linux due to multiple non-trivial issues caused by appimage packaging https://github.com/spacedriveapp/spacedrive/issues/1019, https://github.com/spacedriveapp/spacedrive/issues/1807, https://github.com/spacedriveapp/spacedrive/issues/2039, https://github.com/spacedriveapp/spacedrive/issues/2090. I will soon start working on a flatpak release, and we are also considering creating a native Arch release for Spacedrive. Unfortunatly, for now, the only official release for Spacedrive on Linux is `.deb`. However, there is an unofficial AUR package that is up to date and seems to be working fine: https://aur.archlinux.org/packages/spacedrive-bin. While we do not offer direct support for this release, if you have any issue that is not a direct packaging problem (such as: https://github.com/spacedriveapp/spacedrive/issues/2534) feel free to report it here and we will handle it as any other.

I will close this issue because there is already another issue tracking future linux release here: https://github.com/spacedriveapp/spacedrive/issues/1542. Feel free to comment there if you have any more questions.

**Closed by HeavenVolkoff** 2024-06-25 20:09 UTC
Labels: kind/bug, status/needs-triage
