### ISSUE TITLE
AppImage doesn't work on systems with Glibc < 2.36

### ISSUE THREAD

**Issue by zeet2020** [spacedriveapp/spacedrive#2039] opened 2024-02-01 18:56 UTC
### Describe the bug

on launching the spacedrive.appimage getting empty window with title
![spacedrive](https://github.com/spacedriveapp/spacedrive/assets/1552266/dd12d09a-6317-40c4-8b3e-c138e0e5c506)
on executing on cmdline i see following erroe
```2024-02-01T18:53:11.128607Z  INFO sd_desktop::tauri_plugins: apps/desktop/src-tauri/src/tauri_plugins.rs:80: Internal server listening on: http://127.0.0.1:41467 http://127.0.0.1:42435 http://127.0.0.1:45323 http://127.0.0.1:45139
Gtk-Message: 00:23:12.008: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:23:12.020: Failed to load module "canberra-gtk-module```

i check canberra-gtk-module are already install on my pop-os machine 

### Reproduction

* install pop-os on vm
* download appimage
* try to open the appimage

### Expected behavior

* spacedrive should have worked 

### Platform and versions

```Shell
LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
```

**Comment by HeavenVolkoff** [comment] 2024-02-02 04:58
This seems to be a similar issue to #1993. Are you using X11? Can you reproduce the same issue with the [deb release](https://github.com/spacedriveapp/spacedrive/releases/download/0.2.2/Spacedrive-linux-x86_64.deb)?

**Comment by TheGB0077** [comment] 2024-02-03 20:21
@HeavenVolkoff I found the same issue with the AppImage on today's release, but (seemingly) the issue cannot be reproduced with the deb version.

**Comment by RAVENz46** [comment] 2024-02-10 02:28
I realized that `Exec=usr/bin/spacedrive` in com.spacedrive.desktop.
But I think it should be `Exec=AppRun` or atleast `Exec=/usr/bin/spacedrive`.

**Comment by AutumnalAntlers** [comment] 2024-02-19 11:53
I've had (specific distro aside) exactly the same experience. I don't know the first thing about the tech stack, but blindly tried swapping my system libraries and glibc/linker, into the appimage since they worked for the deb, which is I confirmed is the same binary. No dice.

Loving the vision in the meantime though, thanks to everyone who's making this a reality.

If I find time later this week I'll stick it a chroot, discovering what sockets and environment variables need passed to keep appimage and wayland cooperative, and learning how they're expressed in the appimage configuration as I go. Happy to follow up if I hit any leads.

**Comment by HeavenVolkoff** [comment] 2024-02-20 07:01
> I realized that `Exec=usr/bin/spacedrive` in com.spacedrive.desktop. I think it should be `Exec=AppRun` or atleast `Exec=/usr/bin/spacedrive`.

Is this `.desktop` file generated by some tool? Because the appimage doesn't generate any, and the `deb` has `.desktop` pointing to the correct path:
![image](https://github.com/spacedriveapp/spacedrive/assets/9082460/aa564df1-e2b1-4eac-9ccd-945801b98032)

> The first two big questions are 1). does a prior release work?, and 2). is there a distro that the AppImage _is_ known to work on?

I have been testing all of our AppImage releases in fedora silverblue and arch linux. I can't reproduce this issue on any of those systems. Personally, I think this may be related to X11, all the systems above are running Wayland.

> 0.2.4 works on NixOS
> Nix Derivetion

That is interesting, can someone that is having this problem with the appimage try extracting it and running?
```sh
$> Spacedrive-linux-x86_64.AppImage --appimage-extract
$> ./squashfs-root/AppRun
```

**Comment by AutumnalAntlers** [comment] 2024-02-21 05:04
> fedora silverblue
> Nix Derivation

Awesome, that's exactly what I needed-- and what I great excuse to learn a little Nix!

> I can't reproduce this issue on any of those systems. Personally, I think this may be related to X11, all the systems above are running Wayland.

Ah, sorry, I shouldn't have eluded my Distro & DE! For the record, I was also extracting it from the beginning (Non-FHS System: there are dozens of us!), and have reproduced the issue on Zorin OS w/ Gnome-Wayland and on Guix with Gnome-Wayland, Gnome X11, and XFCE. I've reproduced the lack-of-an-issue on NixOS and Fedora KDE.

I booted Nix for the 2nd time in my life, and copied the contents of the `/nix/store/...-spacedrive-fhs` output into the AppImage root. I was able to transfer the that combined file-tree onto (at-least one) effected distro and run it via `AppRun`, following a few additional band-aids: 
- added a new `lib` to `APPDIR_LIBRARY_PATH`*
- ensured that I was using NixOS's glibc as Spacedrive's interpreter / linker
- ditto for the `AppRun` binary, which I also linked against the new libs

\* I later merged _most_ of these over the existing libraries, but am still exploring which can be moved without breakage. I've written a script that will reduce the combined file-tree to a minimal set overnight based on which files weren't in the original archive, the return value of AppRun, and comparison with a known-good screenshot post-startup.

This update does clarify the nature of the issue, ie. that it is not an issue with AppImage or Display Server environment variables. Hopefully the specifics are clearer once I've shaken the fluff from the tree, but I'm overcoming ignorance through brute-force and may need to see which libraries (if any) can be returned to stock before I have another lead.

**Comment by AutumnalAntlers** [comment] 2024-02-21 21:55
Alright, here are the files from the NixOS overlay that can't be touched without breakage:

```
diff ./AppRun.env ../stock/AppRun.env
< APPDIR_LIBRARY_PATH=[…]:$APPDIR/lib:$APPDIR/runtime/compat/lib/x86_64-linux-gnu/:$APPDIR/lib64
---
> APPDIR_LIBRARY_PATH=[…]
Only in ./lib: libc.so.6
Only in ./lib64: libc.so.6
Only in ./lib64: libdrm.so.2
Only in ./lib64: libEGL.so.1
Only in ./lib64: libgbm.so.1
Only in ./lib64: libGLdispatch.so.0
Only in ./lib64: libGLX.so.0
Only in ./lib64: libstdc++.so.6
Only in ./lib64: libwayland-client.so.0
Only in ./lib64: libwayland-cursor.so.0
Only in ./lib64: libwayland-egl.so.1
Only in ./lib64: libwayland-server.so.0
Only in ./lib64: libX11.so.6
Only in ./lib64: libX11-xcb.so.1
Only in ./lib64: libxcb-randr.so.0
Binary files ./usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 and ../stock/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 differ
Binary files ./usr/lib/x86_64-linux-gnu/libgstgl-1.0.so.0 and ../stock/usr/lib/x86_64-linux-gnu/libgstgl-1.0.so.0 differ
```

I can't reproduce the issue by removing or restoring any of these files, but can by truncating _either_ of the `WebKitWebProcess` and `WebKitNetworkProcess` executables:
```
printf '' > usr/bin/WebKitWebProcess && chmod +x usr/bin/WebKitWebProcess
```

I've `tar`'ed up my `squashfs-root` for [reference](https://github.com/AutumnalAntlers/spacedrive/releases/tag/issue-2039). It should run on any system like so:
```
tar -xzvf squashfs-root.tar.gz && cd squashfs-root && LD_LIBRARY_PATH=./lib ./AppRun
```

Thought it would be slick to package it back up as an AppImage for other users in the meantime, but couldn't figure out how to get it invoked-with or not-requiring the linker and libraries in `./lib{,64}`. Someone who knows more about linking and AppImage could probably untangle them.

I don't intend to invest time diving into the AppImage build process to figure out what needs to change on the backend, but hopefully I've helped to provide more info. In retrospect I probably could have built the `/nix/[…]-spacedrive-fhs` output against an older `nixpkgs` checkout, with ~matching linker and lib versions, but of course that didn't occur to me until it was an issue-- and it still wouldn't have addressed whatever process you use to build these things on the back-end, so w/e.

**Comment by HeavenVolkoff** [comment] 2024-02-22 07:40
> 1: I'd left the ELF interpreter set to a local path, turns out to be non-trivial to resolve in a system-independent way (see: "untangle" above). I updated the instructions to use `patchelf` and bundled the correct interpreter into a [new archive](https://github.com/AutumnalAntlers/spacedrive/releases/tag/issue-2039) which, once again, _should_ work on Pop!_OS— but doesn't on Guix! I get the same transparent window, **ugh**, wonder what I missed. If I ever make an AppImage, I'm just using Nix/Guix to bundle it. **Edit:** not even the un-trimmed tree (with the full NixOS FHS overlay) works on Guix, hmm...

@AutumnalAntlers thank you for the detailed report. I think I now have an idea of what may be causing this problem. Our AppImage ships with two runtimes, a default one for distros with a compatible version of Glibc and a compat one, that embeds a compatible Glibc, for distros that ship an older version of Glibc. Our AppImage is built using packages from Debian bookworm, which ships Glibc version 2.36. Neither of my system ever use the compat runtime because they always have a Glibc newer than Debian stable. However, both PopOS & Ubuntu 22.04 ships Glibc 2.35, Zorin OS 16.3 ships Glibc 2.31 and Guix 1.4.0 ships Glibc 2.33. All of these systems would use the compat runtime because of the older Glibc and considering I wasn't testing this, it is very possible that the `WebKitWebProcess` and `WebKitNetworkProcess` are not executing correctly under this runtime, or, more likely, some of the workarounds I am doing for the AppImage environment are breaking under it.

**Comment by luccahuguet** [comment] 2024-03-07 16:43
same happens here on PopOS 22.04 LTS

**Closed** 2024-05-04 22:30 UTC
Labels: kind/bug, app/desktop, Bug, High priority, Desktop (Client)
