### ISSUE TITLE
[Linux, AppImage, X11] Black Screen on launch v0.2

### ISSUE THREAD

**Issue by newyorkthink** [spacedriveapp/spacedrive#1993] opened 2024-01-25 00:39 UTC
### Describe the bug

always black show, cannot run the latest version

https://github.com/spacedriveapp/spacedrive/assets/87791643/fad5b498-6c5a-4160-8ed1-7042ace0a54b

### Platform and versions

```Shell
appimage
debian
i3wm env
spacedrive version is :0.2.0
```

**Comment by HeavenVolkoff** [comment] 2024-01-27 14:44
@newyorkthink can you reproduce the same problem with the `.deb` version?

**Comment by HeavenVolkoff** [comment] 2024-02-29 06:26
This issue is very likely to be the same as #2039. Closing this, because all the discussion for finding the cause happened there.

**Closed by HeavenVolkoff** 2024-02-29 06:26 UTC
Labels: kind/bug, app/desktop, Bug, High priority, status/needs-more-info
