### ISSUE TITLE
 Preview code files when scrolling without end 

### ISSUE THREAD

**Issue by ncwuguo** [spacedriveapp/spacedrive#2266] opened 2024-03-30 13:37 UTC
### Describe the bug

I used the space bar to preview .py files, but I could scroll all the way down. The code was less than a hundred lines, but I could scroll all the way down to a few thousand lines.

### Platform and versions

```Shell
v0.2.10
Windows 11 家庭中文版 22631.3374
```

**Comment by utkubakir** [comment] 2024-03-31 07:29
Duplicate of #2239

**Closed by utkubakir** 2024-03-31 07:29 UTC
Labels: kind/bug, status/needs-triage
